name: YOLO
server:
  cut-layer: a # or b, c, d
  clients:
    - 2
    - 2
  model: yolo11n
  batch-size: 4
experiment:
  enable: False  #False
  mode: only_cloud
  #mode: only_edge  
rabbit:
  address: 127.0.0.1
  username: guest
  password: guest
  virtual-host: /

debug-mode: False
data: video.mp4
log-path: .
compress:
  enable: True
  num_bit: 8